# syntax = docker/dockerfile:1.0-experimental
FROM golang:1.16.2-alpine3.13 AS base

RUN apk add --no-cache \
    bash \
    build-base \
    curl \
    git \
    make \
    openssh-client

RUN go get sigs.k8s.io/kustomize/kustomize/v4

