name: ci
on:
  push:
jobs:
  run:
    runs-on: self-hosted
    strategy:
      matrix:
        go: [ '1.16', '1.15', '1.14', '1.13' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go run main.go
  build:
    runs-on: self-hosted
    name: builds
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: go build -o main main.go
      - uses: actions/upload-artifact@v2
        with:
          name: test
          path: ./main